// Run with Playwright installed: NODE_PATH=/path/to/node_modules node tests/monster-browser.cjs
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=require('http').createServer((req,res)=>{const p=path.join(root,req.url.split('?')[0]==='/'?'index.html':decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html':'application/octet-stream');let body=fs.readFileSync(p);if(p.endsWith('index.html'))body=body.toString().replace(' let casting=null;',`window.__muTest={place(x,y){playerScene.tilePos=[x,y];playerScene.instanceData[0]=x*100;playerScene.instanceData[1]=y*100;playerScene.instanceData[2]=terrainHeightAt(x,y);gl.bindBuffer(gl.ARRAY_BUFFER,playerScene.instanceBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,playerScene.instanceData);resetCameraToPlayer()},renderAt(t){frame(t)}};let casting=null;`);res.end(body)}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1000,height:650},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.MUMonsters?.ready&&window.MUWorld?.ready&&document.querySelector('#status').textContent.includes('NPC originales'),null,{timeout:90000});
const loaded=await page.evaluate(()=>({count:MUMonsters.active.size,failed:MUMonsters.failed,invalid:[...MUMonsters.active.values()].filter(m=>!MUWorld.canSpawn(m.x,m.y)).length}));assert.equal(loaded.count,32);assert.deepEqual(loaded.failed,[]);assert.equal(loaded.invalid,0);
for(const [name,x,y] of [['west',94,126],['east',175,126],['north',133,87],['south',133,169]]){await page.evaluate(([x,y])=>__muTest.place(x,y),[x,y]);await page.waitForTimeout(1000);const visible=await page.evaluate(()=>[...MUMonsters.active.values()].filter(m=>Number.isFinite(m.screenX)&&m.screenX>0&&m.screenX<innerWidth&&m.screenY>0&&m.screenY<innerHeight).map(m=>m.id));assert(visible.length>=2,name+' needs visible monsters');console.log(name,visible);if(process.env.MU_CAPTURE_DIR)await page.screenshot({path:path.join(process.env.MU_CAPTURE_DIR,'mu-gate-'+name+'.png')})}
for(const [width,height] of [[844,390],[667,320],[568,280]]){
 await page.setViewportSize({width,height});await page.waitForTimeout(500);
 const layout=await page.evaluate(()=>{const b=document.querySelector('#muOpenSkills').getBoundingClientRect(),m=document.querySelector('#muMobileButtons').getBoundingClientRect(),c=document.querySelector('#muCombatControls').getBoundingClientRect();return{buttonTop:b.top,menuBottom:m.bottom,controlsBottom:c.bottom,controlsTop:c.top,viewport:innerHeight}});
 assert(layout.menuBottom>0,'mobile toolbar must be active');assert(layout.buttonTop>=layout.menuBottom+5,'SKILLS must stay below the menu at '+width+'x'+height);
 assert(layout.controlsBottom<=height-10,'combat buttons must fit viewport');
 await page.locator('#muOpenSkills').click();assert.equal(await page.locator('#muSkillWindow').isVisible(),true);await page.locator('#muCloseSkills').click();
 if(process.env.MU_CAPTURE_DIR)await page.screenshot({path:path.join(process.env.MU_CAPTURE_DIR,'mu-controls-'+width+'.png')});console.log('layout',width,height,layout);
}
const respawn=await page.evaluate(()=>{const m=MUCombat.monsters.get('hound-3');MUCombat.damage(m.id,999);m.respawnAt=performance.now()-1;__muTest.renderAt(performance.now());return{alive:m.alive,hp:m.hp,max:m.maxHp,valid:MUWorld.canSpawn(m.x,m.y)}});assert(respawn.alive&&respawn.valid&&respawn.hp===respawn.max);assert.deepEqual(errors,[]);console.log('PASS: 32 loaded monsters, visible groups at four exits, safe respawn, no page errors');}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);process.exit(1)});
